### ISSUE TITLE
why bundle? was the discussion/reason recorded?

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Project_Kernel#12]
why 'bundle' was added? i hope it is not a symfony bundle wondering about the reason this was added.

**Comment by harikt** [comment]
This have been discussed https://groups.google.com/d/msg/auraphp/btIVi6Rxkhk/HJu3aS-ElEQJ .

**Comment by cordoval** [comment]
wished all discussions were in github, thanks for the link

**Comment by cordoval** [comment]
i just hope there is 0 resemblance with the symfony bundles :grin:

**Comment by harikt** [comment]
github is not a place for discussion. Groups works nice.

**Comment by pmjones** [comment]
@cordoval : Zero resemblance as far as I can tell.

**Comment by cordoval** [comment]
yeah, just the name bundle has become to bear very very ... very bad connotations :blush: I need rehab, perhaps i can forgive this instance here.

**Comment by pmjones** [comment]
(/me nods)

I get you. Even after reviewing a thesaurus, I did not find any better name. Sorry to trigger your PTSD.

**Comment by cordoval** [comment]
There is hope we can redeem a term. :+1:
