### ISSUE TITLE
Potential bug : coposer fixed directory

### ISSUE THREAD

**Issue by Grummfy** [auraphp/Aura.Project_Kernel#2]
hello,
In "https://github.com/auraphp/Aura.Project_Kernel/blob/develop-2/src/ProjectContainer.php" I see this part of code $file = "{$base}/vendor/composer/installed.json";

Perhaps you don't know but in composer you can specified the name of "vendor" directory. For me I always call him "library"...

**Comment by harikt** [comment]
not sure what you are pointing here. When you install 3rd party components via composer there will be a vendor folder. Whether you call library or not is the problem.

**Comment by Grummfy** [comment]
The problem is an hard coding path (here called vendor)

**Comment by harikt** [comment]
yes that assumes it needs composer as a hard dependency.

**Comment by harikt** [comment]
@Grummfy is correct here.

It will be good to get rid of this composer stuff. So it can load the `config/default/define.php` file located somewhere.

Yesterday I was trying with `v1` of `Aura.View` inside v2 framework. So I recommend we need to check how things can be resolved.

**Comment by harikt** [comment]
The configuration has been changed and there is new configuration system. Discussion over https://groups.google.com/d/msg/auraphp/Ygk4Of7N2tI/BHYxLkGwXPEJ
