### ISSUE TITLE
Update 2.x branch?

### ISSUE THREAD

**Issue by kumamidori** [auraphp/Aura.Project_Kernel#23]
@koriym 
I'd like to send a PR if I am allowed to fix [Issue#13](https://github.com/auraphp/Aura.Project_Kernel/issues/13) into `2.x`  branch, like [PR14](https://github.com/auraphp/Aura.Project_Kernel/pull/14).
#13 has already been fixed into 4.x ([PR#15](https://github.com/auraphp/Aura.Project_Kernel/pull/15)), but I still use the project with 2.x.
It is because the framework I'm using still depends on 2.x. In other words, [bear/package](https://packagist.org/packages/bear/package) needs `aura/cli` `^2.2` at present.
Then I can't upgrade this package in my project now.

On the other hand, I was concerned that probably releasing 2.x is unnecessary because the 2.x series doesn't support active  PHP versions.

Please give me your opinion.

**Comment by harikt** [comment]
@kumamidori I am forced to do a normal release for this because aura/bin was internally using this package. Hope we can close this issue ?

**Comment by kumamidori** [comment]
@harikt Thank you for the 2.2 release! 
Now that it is released, I think you can close this [Issue#23](https://github.com/auraphp/Aura.Project_Kernel/issues/23).
